/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package account.management.system;

import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class DELETE extends javax.swing.JFrame {
    String url = "jdbc:mysql://localhost:3306";
    String username = "root";
    String password = "";
    String TBname;
    /**
     * Creates new form DELETE
     */
    public DELETE() {
        initComponents();
    }
    
    public DELETE(String dbname) {
        initComponents();
        checkCon();
        TBname = dbname;
    }
    
    private void checkCon() {
        try (Connection con = DriverManager.getConnection(url, username, password)) {
            if (con != null) {
                con.close();
            }  
        } catch (SQLException e) {
            new CONERROR().setVisible(true); 
            throw new IllegalStateException(e);
        } 
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        accnumField = new javax.swing.JTextField();
        banner = new javax.swing.JLabel();
        delButton = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        accnumField.setFont(new java.awt.Font("Ebrima", 0, 18)); // NOI18N
        accnumField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accnumFieldActionPerformed(evt);
            }
        });

        banner.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        banner.setText("Account number:");

        delButton.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        delButton.setText("Delete");
        delButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                delButtonMouseClicked(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(31, 31, 31)
                .add(banner)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(delButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 147, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(accnumField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 270, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap(80, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(banner, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 40, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(accnumField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 40, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(delButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 57, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(56, 56, 56))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void accnumFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accnumFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_accnumFieldActionPerformed

    private void delButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_delButtonMouseClicked
         String searchData = accnumField.getText();
        
        try (Connection con = DriverManager.getConnection(url, username, password)) {
            Statement db = null;
            Statement stmt = null;
            String initdbquery = "USE account_management_system;";
            String query = "DELETE FROM `" + TBname + "` WHERE `" + TBname + "`.`Entry number` = " + searchData + ";";

            try {
                db = con.createStatement();
                stmt = con.createStatement();
                db.execute(initdbquery);
                stmt.execute(query);
                
                JOptionPane.showMessageDialog(null,"Entry '" + searchData + "' data has deleted .");
            }
            catch (SQLException ex){
                // handle any errors
                JOptionPane.showMessageDialog(null,"Entry " + searchData + " not found.");
                ex.printStackTrace();
            }
            finally {
                if (db != null) {
                    try {
                        db.close();
                    } 
                    catch (SQLException sqlEx) { }
                    db = null;
                }
                    
                if (stmt != null) {
                    try {
                        stmt.close();
                    } 
                    catch (SQLException sqlEx) { }
                        stmt = null;
                    }

                    if (con != null) {
                        con.close();
                        this.dispose();
                    }
                }
            } 
        catch (SQLException e) {
            JOptionPane.showMessageDialog(null,"Can't connect to the database");
            throw new IllegalStateException(e);
        }
    }//GEN-LAST:event_delButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DELETE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DELETE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DELETE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DELETE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DELETE().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField accnumField;
    private javax.swing.JLabel banner;
    private javax.swing.JToggleButton delButton;
    // End of variables declaration//GEN-END:variables
}
